// <auto-generated />
namespace MyFYP.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class StoreRegistration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreRegistration));
        
        string IMigrationMetadata.Id
        {
            get { return "202002051448428_StoreRegistration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
